### ISSUE TITLE
Thanks for making this but network issue

### ISSUE THREAD

**Issue by AverTry** [patrickfav/pihole-unbound-docker#1]
Error response from daemon: invalid config for network pihole_dns_network: invalid endpoint settings:
no configured subnet or ip-range contain the IP address 172.21.200.3
![image](https://github.com/patrickfav/pihole-unbound-docker/assets/72357571/8e956536-f66b-4234-bb3e-b642f7ef0640)

Ran fine till the network part. It created the network but then say's it can't find the network?
refuses to build container.

**Comment by patrickfav** [comment]
Not sure if this was the problem, but I only set the ip range to 172.21.200.128/25, now its allowed the full /24 subnet. Please try again.

**Comment by AverTry** [comment]
Thanks for responding, turned out to be dns port 53 was in use by another program.
This was the solution for me on ubuntu.
[https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f](https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f)
